#%RAML 1.0
---
title: REST API pour le travail de session du cours INF5190
baseUri: http://localhost:5000
mediaType: application/json

types:
    Installations:
        properties:
            glissades:
                type: Glissade[]
                required: true
            patinoires:
                type: Patinoire[]
                required: true
            piscines:
                type: Piscine[]
                required: true
    Arrondissement:
        properties:
            nom_arr:
                type: string
            cle:
                type: string
            date_maj:
                type: datetime
                description: Doit respecter le format ISO8601: YYYY-MM-DD HH-MM-SS
                example: 2021-10-18 13:45:13
    ArrondissementPatch:
        properties:
            nom_arr:
                type: string
                required: false
            cle:
                type: string
                required: false
            date_maj:
                type: datetime
                description: Doit respecter le format ISO8601: YYYY-MM-DD HH-MM-SS
                example: 2021-10-18 13:45:13
                required: false
    Glissade:
        properties:
            nom:
                type: string
            arrondissement:
                type: Arrondissement
            ouvert:
                type: boolean
                description: Peut uniquement être 0 ou 1
            deblaye:
                type: boolean
                description: Peut uniquement être 0 ou 1
            condition:
                type: string
                default: N/A
    GlissadePatch:
        properties:
            nom:
                type: string
                required: false
            arrondissement:
                type: ArrondissementPatch
                required: false
            ouvert:
                type: boolean
                description: Peut uniquement être 0 ou 1
                required: false
            deblaye:
                type: boolean
                description: Peut uniquement être 0 ou 1
                required: false
            condition:
                type: string
                required: false
                default: N/A
    Patinoire:
        properties:
            nom_arr:
                type: string
            nom_pat:
                type: string
    PatinoirePatch:
        properties:
            nom_arr:
                type: string
                required: false
            nom_pat:
                type: string
                required: false
    Piscine:
        properties:
            id_uev:
                type: integer
            type:
                type: string
            nom:
                type: string
            arrondisse:
                type: string
            adresse:
                type: string
                required: false
            propriete:
                type: string
                required: false
            gestion:
                type: string
                required: false
            point_x:
                type: string
            point_y:
                type: string
            equipeme:
                type: string
                required: false
            longitude:
                type: number
            latitude:
                type: number
    PiscinePatch:
        properties:
            id_uev:
                type: integer
                required: false
            type:
                type: string
                required: false
            nom:
                type: string
                required: false
            arrondisse:
                type: string
                required: false
            adresse:
                type: string
                required: false
            propriete:
                type: string
                required: false
            gestion:
                type: string
                required: false
            point_x:
                type: string
                required: false
            point_y:
                type: string
                required: false
            equipeme:
                type: string
                required: false
            longitude:
                type: number
                required: false
            latitude:
                type: number
                required: false
    Error:
        properties:
            error:
                type: string

/api:
    /installations:
        get:
            description: Retourne la liste de toutes les installations
            queryParameters:
                arrondissement:
                    displayName: arrondissement
                    type: string
                    description: Si ajouté, retourne la liste de toutes les installations selon cet `arrondissement`
                    example: "/api/installations?arrondissement=Ahuntsic"
                    required: false
            responses:
                200:
                    description: Retourne une liste d'installations
                    body:
                        application/json:
                            type: Installations
                            example: |
                                {
                                    "glissades": [
                                        {
                                        "nom": "Aire de glissade ,Don-Bosco",
                                        "arrondissement": {
                                        "nom_arr": "Rivière-des-Prairies - Pointe-aux-Trembles",
                                        "cle": "rdp",
                                        "date_maj": "2021-10-18 13:45:13"
                                        },
                                        "ouvert": 0,
                                        "deblaye": 0,
                                        "condition": "N/A"
                                        }
                                    ],
                                    "patinoires": [
                                        {
                                        "nom_arr": "Ahuntsic - Cartierville",
                                        "nom_pat": "Aire de glissade, Ahuntsic ()"
                                        },
                                        {
                                        "nom_arr": "Ahuntsic - Cartierville",
                                        "nom_pat": "Aire de glissade, Des Hirondelles ()"
                                        }
                                    ],
                                    "piscines": []
                                }
                400:
                    description: Un paramètre différent d'`arrondissement` a été précisé
                    body:
                        application/json:
                            type: Error
                            example: |
                                {
                                    "error": "Le seul paramètre possible est arrondissement"
                                }
                404:
                    description: Aucune installation n'a été trouvée
                    body:
                        application/json:
                            type: Error
                            example: |
                                {
                                    "error": "Aucune installation n'a été trouvée"
                                }
    /installation:
        /{nom}:
            get:
                description: Retourne toute l'information disponible sur l'installation qui a le nom passé dans l'url
                example: "/api/installations/Parc Beaulac"
                responses:
                    200:
                        description: L'installation existe et l'api retourne ses informations
                        body:
                            application/json:
                                description: L'installation est soit une glissade, soit une patinoire soit une piscine
                            example: |
                                {
                                    "id_uev": 4030363,
                                    "type": "Jeu d'eau",
                                    "nom": "Parc Beaulac",
                                    "arrondisse": "Saint-Laurent",
                                    "adresse": "1 145, Rue Élizabeth",
                                    "propriete": "Municipale",
                                    "gestion": "Municipale",
                                    "point_x": "290934,0231",
                                    "point_y": "5042211675",
                                    "equipeme": "",
                                    "long": -73.677489,
                                    "lat": 45.51968
                                }
                    404:
                        description: L'installation n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Aucune installation n'a été trouvée"
                                    }
    /glissades:
        get:
            description: Retourne toutes les glissades
            responses:
                200:
                    description: Il y a au moins une glissade dans la base de donné et elle est retournée
                    body:
                        application/json:
                            type: Glissade[]
                        example: |
                            [
                                {
                                    "nom": "Aire de glissade ,Don-Bosco",
                                    "arrondissement": {
                                    "nom_arr": "Rivière-des-Prairies - Pointe-aux-Trembles",
                                    "cle": "rdp",
                                    "date_maj": "2021-10-18 13:45:13"
                                    },
                                    "ouvert": 0,
                                    "deblaye": 0,
                                    "condition": "N/A"
                                },
                                {
                                    "nom": "Aire de glissade,François-Vaillancourt",
                                    "arrondissement": {
                                    "nom_arr": "Rivière-des-Prairies - Pointe-aux-Trembles",
                                    "cle": "rdp",
                                    "date_maj": "2021-10-18 13:45:13"
                                    },
                                    "ouvert": 0,
                                    "deblaye": 0,
                                    "condition": "N/A"
                                }
                            ]
                404:
                    description: Il n'y a aucune glissade dans la base de données
                    body:
                        application/json:
                            type: Error
                            example: |
                                {
                                    "error": "Il n'y a aucune glissade"
                                }
    /glissade:
        /{nom}:
            get:
                description: Retourne la glissade qui a comme nom `nom`
                example: "api/glisade/Aire de glissade ,Don-Bosco"
                responses:
                    200:
                        description: Retourne la glissade
                        body:
                            application/json:
                                type: Glissade
                                example: |
                                    {
                                        "nom": "Aire de glissade ,Don-Bosco",
                                        "arrondissement": {
                                            "nom_arr": "Rivière-des-Prairies - Pointe-aux-Trembles",
                                            "cle": "rdp",
                                            "date_maj": "2021-10-18 13:45:13"
                                        },
                                        "ouvert": 0,
                                        "deblaye": 0,
                                        "condition": "N/A"
                                    }
                    404:
                        description: La glissade n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La glissade n'existe pas"
                                    }
            delete:
                description: Supprime la glissade qui a comme nom `nom`
                example: "/api/glissade/Aire de glissade ,Don-Bosco"
                responses:
                    200:
                        description: La glissade a été suprimée
                        body:
                            application/json:
                                type: Glissade
                                example: |
                                    {
                                        "nom": "Aire de glissade ,Don-Bosco",
                                        "arrondissement": {
                                            "nom_arr": "Rivière-des-Prairies - Pointe-aux-Trembles",
                                            "cle": "rdp",
                                            "date_maj": "2021-10-18 13:45:13"
                                        },
                                        "ouvert": 0,
                                        "deblaye": 0,
                                        "condition": "N/A"
                                    }
                    404:
                        description: La glissade n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La glissade n'existe pas"
                                    }
                    500:
                        description: Il y a eu un problème avec la supression de la glissade
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Il y a eu une erreur avec la suppression de la glissade"
                                    }
            put:
                description: Modifie toutes les valeurs de la glissade
                example: "api/glisade/Aire de glissade ,Don-Bosco"
                body:
                    application/json:
                        type: Glissade
                        example: |
                            {
                                "nom": "nouveau nom",
                                "arrondissement": {
                                    "nom_arr": "nouveau nom",
                                    "cle": "nouvelle cle",
                                    "date_maj": "2021-10-19 13:45:13"
                                },
                                "ouvert": 1,
                                "deblaye": 1,
                                "condition": "nouvelle condition"
                            }
                responses:
                    200:
                        description: La glissade a été modifiée
                        body:
                            application/json:
                                type: Glissade
                                example: |
                                    {
                                        "nom": "nouveau nom",
                                        "arrondissement": {
                                            "nom_arr": "nouveau nom",
                                            "cle": "nouvelle cle",
                                            "date_maj": "nouvelle date"
                                        },
                                        "ouvert": 0,
                                        "deblaye": 0,
                                        "condition": "N/A"
                                    }
                    400:
                        description: Le JSON envoyé ne respecte pas le schema
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Le fichier JSON envoyé ne respecte pas le schema"
                                    }
                    404:
                        description: La glissade n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La glissade n'existe pas"
                                    }
                    500:
                        description: Il y a eu une erreur en modifiant la glissade
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Il y a eu une erreur avec la modification de la glissade"
                                    }
            patch:
                description: Modifie quelques valeurs de la glissade
                example: "api/glisade/Aire de glissade ,Don-Bosco"
                body:
                    application/json:
                        type: GlissadePatch
                        example: |
                            {
                                "nom": "nouveau nom",
                                "ouvert": 1
                            }
                responses:
                    200:
                        description: La glissade a été modifiée
                        body:
                            application/json:
                                type: Glissade
                                example: |
                                    {
                                        "nom": "nouveau nom",
                                        "arrondissement": {
                                            "nom_arr": "Rivière-des-Prairies - Pointe-aux-Trembles",
                                            "cle": "rdp",
                                            "date_maj": "2021-10-18 13:45:13"
                                        },
                                        "ouvert": 1,
                                        "deblaye": 0,
                                        "condition": "N/A"
                                    }
                    400:
                        description: Le JSON envoyé ne respecte pas le schema
                        body:
                            application/json:
                                type: Glissade
                                example: |
                                    {
                                        "error": "Le fichier JSON envoyé ne respecte pas le schema"
                                    }
                    404:
                        description: La glissade n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La glissade n'existe pas"
                                    }
                    500:
                        description: Il y a eu une erreur en modifiant la glissade
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Il y a eu une erreur avec la modification de la glissade"
                                    }
    /patinoires:
        get:
            description: Retourne toutes les patinoires
            responses:
                200:
                    description: Il y a au moins une patinoire dans la base de donné et elle est retournée
                    body:
                        application/json:
                            type: Patinoire[]
                        example: |
                            [
                                {
                                    "nom_arr": "Anjou",
                                    "nom_pat": "Anneau de glace, Parc Lucie-Bruneau (PPL)"
                                },
                                {
                                    "nom_arr": "Côte-des-Neiges - Notre-Dame-de-Grâce",
                                    "nom_pat": "Aire de glissade, Parc Confédération ()"
                                }
                            ]
                404:
                    description: Il n'y a aucune patinoire dans la base de données
                    body:
                        application/json:
                            type: Error
                            example: |
                                {
                                    "error": "Il n'y a aucune patinoire"
                                }
    /patinoire:
        /{nom_pat}:
            get:
                description: Retourne la patinoire qui a comme nom `nom_pat`
                example: "/api/patinoire/Anneau de glace, Parc Lucie-Bruneau (PPL)"
                responses:
                    200:
                        description: Retourne la patinoire
                        body:
                            application/json:
                                type: Patinoire
                                example: |
                                    {
                                        "nom_arr": "Anjou",
                                        "nom_pat": "Anneau de glace, Parc Lucie-Bruneau (PPL)"
                                    }
                    404:
                        description: La patinoire n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La patinoire n'existe pas"
                                    }
            delete:
                description: Supprime la patinoire qui a comme nom `nom_pat`
                example: "/api/patinoire/Anneau de glace, Parc Lucie-Bruneau (PPL)"
                responses:
                    200:
                        description: La patinoire a été suprimée
                        body:
                            application/json:
                                type: Patinoire
                                example: |
                                    {
                                        "nom_arr": "Anjou",
                                        "nom_pat": "Anneau de glace, Parc Lucie-Bruneau (PPL)"
                                    }
                    404:
                        description: La patinoire n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La patinoire n'existe pas"
                                    }
                    500:
                        description: Il y a eu un problème avec la supression de la patinoire
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Il y a eu une erreur avec la suppression de la patinoire"
                                    }
            put:
                description: Modifie toutes les valeurs de la patinoire
                example: "/api/patinoire/Anneau de glace, Parc Lucie-Bruneau (PPL)"
                body:
                    application/json:
                        type: Patinoire
                        example: |
                            {
                                "nom_arr": "Nouvelle valeur arr",
                                "nom_pat": "Nouvelle valeur nom"
                            }
                responses:
                    200:
                        description: La patinoire a été modifiée
                        body:
                            application/json:
                                type: Patinoire
                                example: |
                                    {
                                        "nom_arr": "nouveau arr",
                                        "nom_pat": "nouveau nom"
                                    }
                    400:
                        description: Le JSON envoyé ne respecte pas le schema
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Le fichier JSON envoyé ne respecte pas le schema"
                                    }
                    404:
                        description: La patinoire n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La patinoire n'existe pas"
                                    }
                    500:
                        description: Il y a eu une erreur en modifiant la patinoire
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Il y a eu une erreur avec la modification de la patinoire"
                                    }
            patch:
                description: Modifie quelques valeurs de la patinoire
                example: "/api/patinoire/Anneau de glace, Parc Lucie-Bruneau (PPL)"
                body:
                    application/json:
                        type: PatinoirePatch
                        example: |
                            {
                                "nom_arr": "nouveau arr",
                            }
                responses:
                    200:
                        description: La patinoire a été modifiée
                        body:
                            application/json:
                                type: Patinoire
                                example: |
                                    {
                                        "nom_pat": "Anneau de glace, Parc Lucie-Bruneau (PPL)",
                                        "nom_pat": "nouveau arr",
                                    }
                    400:
                        description: Le JSON envoyé ne respecte pas le schema
                        body:
                            application/json:
                                type: Patinoire
                                example: |
                                    {
                                        "error": "Le fichier JSON envoyé ne respecte pas le schema"
                                    }
                    404:
                        description: La patinoire n'existe pas
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "La patinoire n'existe pas"
                                    }
                    500:
                        description: Il y a eu une erreur en modifiant la patinoire
                        body:
                            application/json:
                                type: Error
                                example: |
                                    {
                                        "error": "Il y a eu une erreur avec la modification de la patinoire"
                                    }
    /piscines:
        get:
            description: Retourne toutes les piscines
            responses:
                200:
                    description: Il y a au moins une piscine dans la base de donné et elle est retournée
                    body:
                        application/json:
                            type: Piscine[]
                        example: |
                            [
                                {
                                    "id_uev": 5015454,
                                    "type": "Pataugeoire",
                                    "nom": "Saint-Jean-Baptiste",
                                    "arrondisse": "Rivière-des-Prairies–Pointe-aux-Trembles",
                                    "adresse": "1 048, Boulevard Saint-Jean-Baptiste",
                                    "propriete": "Municipale",
                                    "gestion": "Municipale",
                                    "point_x": "304846,2071",
                                    "point_y": "5055625,72",
                                    "equipeme": "",
                                    "long": -73.49941,
                                    "lat": 45.640521
                                },
                                {
                                    "id_uev": 1050716,
                                    "type": "Jeu d'eau",
                                    "nom": "Parc Normand Dawe",
                                    "arrondisse": "Verdun",
                                    "adresse": "1 060, Rue Woodland",
                                    "propriete": "Municipale",
                                    "gestion": "Municipale",
                                    "point_x": "298647,5623",
                                    "point_y": "5034733453",
                                    "equipeme": "",
                                    "long": -73.578667,
                                    "lat": 45.4525
                                }
                            ]
                404:
                    description: Il n'y a aucune piscine dans la base de données
                    body:
                        application/json:
                            type: Error
                            example: |
                                {
                                    "error": "Il n'y a aucune piscine"
                                }
    /piscine:
        /{type}:
            /{nom}:
                get:
                    description: Retourne la piscine qui a comme nom `nom` et comme type `type`
                    example: "api/piscine/Pataugeoire/Saint-Jean-Baptiste"
                    responses:
                        200:
                            description: Retourne la piscine
                            body:
                                application/json:
                                    type: Piscine
                                    example: |
                                        {
                                            "id_uev": 5015454,
                                            "type": "Pataugeoire",
                                            "nom": "Saint-Jean-Baptiste",
                                            "arrondisse": "Rivière-des-Prairies–Pointe-aux-Trembles",
                                            "adresse": "1 048, Boulevard Saint-Jean-Baptiste",
                                            "propriete": "Municipale",
                                            "gestion": "Municipale",
                                            "point_x": "304846,2071",
                                            "point_y": "5055625,72",
                                            "equipeme": "",
                                            "long": -73.49941,
                                            "lat": 45.640521
                                        }          
                delete:
                    description: Supprime la piscine qui a comme nom `nom` et comme type `type`
                    example: "api/piscine/Pataugeoire/Saint-Jean-Baptiste"
                    responses:
                        200:
                            description: La piscine a été suprimée
                            body:
                                application/json:
                                    type: Piscine
                                    example: |
                                        {
                                            "id_uev": 5015454,
                                            "type": "Pataugeoire",
                                            "nom": "Saint-Jean-Baptiste",
                                            "arrondisse": "Rivière-des-Prairies–Pointe-aux-Trembles",
                                            "adresse": "1 048, Boulevard Saint-Jean-Baptiste",
                                            "propriete": "Municipale",
                                            "gestion": "Municipale",
                                            "point_x": "304846,2071",
                                            "point_y": "5055625,72",
                                            "equipeme": "",
                                            "long": -73.49941,
                                            "lat": 45.640521
                                        }
                        404:
                            description: La piscine n'existe pas
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "La piscine n'existe pas"
                                        }
                        500:
                            description: Il y a eu un problème avec la supression de la piscine
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "Il y a eu une erreur avec la suppression de la piscine"
                                        }
                put:
                    description: Modifie toutes les valeurs de la piscine qui a comme nom `nom` et comme type `type`
                    example: "api/piscine/Pataugeoire/Saint-Jean-Baptiste"
                    body:
                        application/json:
                            type: Piscine
                            example: |
                                {
                                    "id_uev": 0000000,
                                    "type": "nouveau type",
                                    "nom": "nouveau nom",
                                    "arrondisse": "nouvel arrondissement",
                                    "adresse": "nouvelle adresse",
                                    "propriete": "nouvelle propriete",
                                    "gestion": "nouvelle gesiton",
                                    "point_x": "000000,00",
                                    "point_y": "000000,00",
                                    "equipeme": "nouveaux equipements",
                                    "long": 00.000000,
                                    "lat": 00.000000
                                }
                    responses:
                        200:
                            description: La piscine a été modifiée
                            body:
                                application/json:
                                    type: Piscine
                                    example: |
                                        {
                                            "id_uev": 0000000,
                                            "type": "nouveau type",
                                            "nom": "nouveau nom",
                                            "arrondisse": "nouvel arrondissement",
                                            "adresse": "nouvelle adresse",
                                            "propriete": "nouvelle propriete",
                                            "gestion": "nouvelle gesiton",
                                            "point_x": "000000,00",
                                            "point_y": "000000,00",
                                            "equipeme": "nouveaux equipements",
                                            "long": 00.000000,
                                            "lat": 00.000000
                                        }
                        400:
                            description: Le JSON envoyé ne respecte pas le schema
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "Le fichier JSON envoyé ne respecte pas le schema"
                                        }
                        404:
                            description: La piscine n'existe pas
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "La piscine n'existe pas"
                                        }
                        500:
                            description: Il y a eu une erreur en modifiant la piscine
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "Il y a eu une erreur avec la modification de la piscine"
                                        }
                patch:
                    description: Modifie quelques valeurs de la piscine qui a comme nom `nom` et comme type `type`
                    example: "api/piscine/Pataugeoire/Saint-Jean-Baptiste"
                    body:
                        application/json:
                            type: PiscinePatch
                            example: |
                                {
                                    "id_uev": "0000000",
                                    "equipeme": "nouveaux equipements"
                                }
                    responses:
                        200:
                            description: La piscine a été modifiée
                            body:
                                application/json:
                                    type: Piscine
                                    example: |
                                        {
                                            "id_uev": 0000000,
                                            "type": "Pataugeoire",
                                            "nom": "Saint-Jean-Baptiste",
                                            "arrondisse": "Rivière-des-Prairies–Pointe-aux-Trembles",
                                            "adresse": "1 048, Boulevard Saint-Jean-Baptiste",
                                            "propriete": "Municipale",
                                            "gestion": "Municipale",
                                            "point_x": "304846,2071",
                                            "point_y": "5055625,72",
                                            "equipeme": "nouveaux equipements",
                                            "long": -73.49941,
                                            "lat": 45.640521
                                        }
                        400:
                            description: Le JSON envoyé ne respecte pas le schema
                            body:
                                application/json:
                                    type: Piscine
                                    example: |
                                        {
                                            "error": "Le fichier JSON envoyé ne respecte pas le schema"
                                        }
                        404:
                            description: La piscine n'existe pas
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "La piscine n'existe pas"
                                        }
                        500:
                            description: Il y a eu une erreur en modifiant la piscine
                            body:
                                application/json:
                                    type: Error
                                    example: |
                                        {
                                            "error": "Il y a eu une erreur avec la modification de la piscine"
                                        }